---
- name: Configure autodeploy job templates on main AAP
  hosts: hypervisor
  gather_facts: false
  vars_files:
    - ../myvars
  vars:
    ctrl_host: "https://aap.{{ vault_domain }}"
    ctrl_user: "admin"
    ctrl_pass: "{{ gateway_admin_password }}"

  tasks:
    - name: Update JT - Deploy Test AAP to 01-vm-setup
      ansible.controller.job_template:
        name: "Deploy Test AAP"
        playbook: "aap-autodeploy/01-vm-setup.yml"
        controller_host: "{{ ctrl_host }}"
        controller_username: "{{ ctrl_user }}"
        controller_password: "{{ ctrl_pass }}"
        validate_certs: false
      delegate_to: localhost

    - name: Add credentials to JT - 02 Infra Config
      ansible.controller.job_template:
        name: "Deploy Test AAP - 02 Infra Config"
        credentials:
          - "hypervisor cred"
          - "local vault cred of myvars"
        controller_host: "{{ ctrl_host }}"
        controller_username: "{{ ctrl_user }}"
        controller_password: "{{ ctrl_pass }}"
        validate_certs: false
      delegate_to: localhost

    - name: Add credentials to JT - 03 AAP Install
      ansible.controller.job_template:
        name: "Deploy Test AAP - 03 AAP Install"
        credentials:
          - "hypervisor cred"
          - "local vault cred of myvars"
        controller_host: "{{ ctrl_host }}"
        controller_username: "{{ ctrl_user }}"
        controller_password: "{{ ctrl_pass }}"
        validate_certs: false
      delegate_to: localhost

    - name: Create JT - 04 AAP Config
      ansible.controller.job_template:
        name: "Deploy Test AAP - 04 AAP Config"
        description: "Config-as-code: post-install configuration. Extra vars: vm_name, vm_ip"
        project: "AAP Advanced Features"
        inventory: "Localhost"
        playbook: "aap-autodeploy/04-aap-config.yml"
        credentials:
          - "local vault cred of myvars"
        become_enabled: false
        ask_variables_on_launch: true
        verbosity: 1
        execution_environment: "Orchestrator EE"
        controller_host: "{{ ctrl_host }}"
        controller_username: "{{ ctrl_user }}"
        controller_password: "{{ ctrl_pass }}"
        validate_certs: false
      delegate_to: localhost
